init

diff --git a/scripts/gist-id b/scripts/gist-id
--- a/scripts/gist-id
+++ b/scripts/gist-id
@@ -2,23 +2,27 @@
 { set +x; } 2>/dev/null
 
 usage() {
-    echo "usage: $(basename $0) path" 1>&2
-    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
+    echo "usage: $(basename $0) [path ...]" 1>&2
+    [ "$1" = "-h" ] || [ "$1" = "--help" ]; exit
 }
 
-[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"
+[ "$1" = "-h" ] || [ "$1" = "--help" ] && usage "$@"
 
-[[ $# != 1 ]] && usage
+while [[ $# != 0 ]]; do
+    cd "$1" || exit
+    shift
+    ! [ -e .git ] && continue
+    ! [ -e .git/config ] && continue
+    url="$(git remote -v | grep gist.github.com | head -1 | awk '{print $2}')"
+    [[ -z "$url" ]] && continue
 
-cd "$1" || exit
-! [ -e .git ] && exit
-! [ -e .git/config ] && exit
-url="$(git remote -v | grep gist.github.com | head -1 | awk '{print $2}')"
-[[ -z "$url" ]] && exit
-
-# https://gist.github.com/<id>.git
-[[ "$url" == "https"* ]] && echo "$url" | awk -F":" '{print $2}' | sed 's/.\{4\}$//' && exit
-
-# git@gist.github.com:<id>.git
-[[ "$url" == "git@"* ]] && echo "$url" | awk -F":" '{print $2}' | sed 's/.\{4\}$//' && exit
-echo "ERROR: $url" 1>&2 && exit 1
+    # https://gist.github.com/<id>.git
+    [[ "$url" == "https"* ]] && {
+        echo "$url" | awk -F":" '{print $2}' | sed 's/.\{4\}$//' && continue
+    }
+    # git@gist.github.com:<id>.git
+    [[ "$url" == "git@"* ]] && {
+        echo "$url" | awk -F":" '{print $2}' | sed 's/.\{4\}$//' && continue
+    }
+    echo "ERROR: $url" 1>&2 && exit 1
+done;:
